name: bitacora
description: "BITACORA de Transporte"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  flutter_svg: ^2.2.3
  lottie: ^3.1.2
  cached_network_image: ^3.3.1

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.7

  # HTTP & Networking
  dio: ^5.9.1
  socket_io_client: ^3.1.4

  # Dependency Injection
  get_it: ^8.3.0

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.4

  # Forms
  flutter_form_builder: ^10.3.0+1
  formz: ^0.8.0

  # Maps & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2

  # Images
  image_picker: ^1.2.1
  image_cropper: ^9.1.0

  # Permissions
  permission_handler: ^12.0.1

  # JWT
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/lottie/
